### ISSUE TITLE
Flushing Volumes Dialog not displayed correctly

### ISSUE THREAD

**Issue by kadrim** [flathub/com.bambulab.BambuStudio#1]
### Bambu Studio Version

1.8.2.56

### Where is the application from?

Flathub

### OS version

Ubuntu 22.04

### Printer

Bambu Lab X1C

### How to reproduce

1. Install Bambu Studio from Flatpak
2. Start Bambu Studio
3. Switch to Tab "Prepare"
4. Add some Filaments
5. Click on "Flushing Volumes"

### Actual results

The Dialog is not displayed correctly:

![grafik](https://github.com/bambulab/BambuStudio/assets/8304331/74d1bc25-7423-43fd-97a6-4f1a85c12b94)

### Expected results

Full Dialog Displayed, i.e.:

![grafik](https://github.com/bambulab/BambuStudio/assets/8304331/b02cacaf-69c1-45b0-8ba8-855b614c6307)

I first came across this issue on my steam deck (steam os / arch linux) and wanted to give the new flatpak version of bambu studio a try.

Afterwards i tried to find out if it was related to the flatpak build by using my ubuntu 22.04 machine as reference. On ubuntu the AppImage build is displaying the "flushing volumes" correctly. Then i installed the flatpak version also on my ubuntu22.04 and there the dialog is broken so most probably only related to the flatpak build.

**Comment by hadess** [comment]
There will be a test build in https://github.com/flathub/com.bambulab.BambuStudio/pull/12 shortly
