### ISSUE TITLE
Crash on startup after installing the network plug-in

### ISSUE THREAD

**Issue by hho** [flathub/com.bambulab.BambuStudio#17]
On first launch, it downloads the Bambu network plug-in. It then crashes.
Every further launch crashes directly after showing the main window:

```
terminate called after throwing an instance of 'nlohmann::detail::type_error'
  what():  [json.exception.type_error.302] type must be boolean, but is null
```

The Appimage from Bambu works fine, though – that's why I'm reporting it here.

Version: 1.9.0 Public Beta
Branch: stable
Commit: a87a817700d1058f590ced6ead1de92f8f3355dfcb5a03ec011605c6c71db285

**Comment by hadess** [comment]
That code isn't something that's changed in the Flatpak, so even if the problem only happens in a Flatpak environment, it's an upstream bug. I also don't have access to the network plugin's code, BambuLab developers do ;)

Best to file it upstream.

**Comment by hho** [comment]
After deleting `~/.var/app/com.bambulab.BambuStudio` and setting it up again it now works.
Sorry for the noise.
