### ISSUE TITLE
Local build

### ISSUE THREAD

**Issue by MackBambu** [flathub/com.bambulab.BambuStudio#23]
When I run local-build.sh and build Bambu Studio, it often crashes due to huge memory usage. Is this normal?

![OzGqdt71fb](https://github.com/flathub/com.bambulab.BambuStudio/assets/169036319/83947552-7e62-4239-a67a-69864ca1a41f)

**Comment by hadess** [comment]
> When I run local-build.sh and build Bambu Studio, it often crashes due to huge memory usage. Is this normal?

Yes, it's normal, [the upstream](https://github.com/bambulab/BambuStudio/blob/master/BuildLinux.sh) also has a minimum requirement of 10GB of free RAM, which I guess would be higher in this case as we're also sandboxed.
