### ISSUE TITLE
Cant add remote access to install bambu studio

### ISSUE THREAD

**Issue by KOGJet** [flathub/com.bambulab.BambuStudio#26]
when using the script flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
I get the error below
error: Flatpak system operation ConfigureRemote not allowed for user

**Comment by hadess** [comment]
You need to run that line as root, as the error message shows.

Note that setting up Flatpak isn't something we can help with, your distribution's forums should be able to help though.
