### ISSUE TITLE
Camera crashes app

### ISSUE THREAD

**Issue by KOGJet** [flathub/com.bambulab.BambuStudio#27]
I'm using a samsung Chromebook with penguin Linux. ive tried to use the Ubuntu fedora and flathub versions of Bambu studio and view my camera but it does one of three things. Crashes immediately after I hit play or says device cannot handle more conversations/reset the printer and retry which is always followed by an immediate crash. I've seen someone say the jpeg of the app image can be downgraded and that should work. Any ideas?

**Comment by JulianGro** [comment]
No ideas, just mentioning that it works for me on x86_64.

**Comment by hadess** [comment]
We can't help you with the Ubuntu or Fedora versions of Bambu Studio, just with the Flathub version.

Does this still happen with the "1.9.3" version that was uploaded last week, and if so, what are the errors on the command-line? Also make sure that the Network plugin is installed, and is the latest version.

**Comment by hadess** [comment]
No updates, closing.
