### ISSUE TITLE
Text rendering gets cut off in certain calibration page locations

### ISSUE THREAD

**Issue by Nightfirecat** [flathub/com.bambulab.BambuStudio#29]
In calibration pages, some of the rendered text is cropped, as shown below:

![cropped-text-1](https://github.com/flathub/com.bambulab.BambuStudio/assets/2199511/01c9e4aa-7528-4af2-a04c-c8307362e0d3)
![cropped-text-2](https://github.com/flathub/com.bambulab.BambuStudio/assets/2199511/20f576b9-8006-488b-9a09-dda3fa70006b)

**Comment by hadess** [comment]
Does this still happen?

**Comment by Nightfirecat** [comment]
Yes

**Comment by hadess** [comment]
Could you please file a bug under BambuStudio itself? Issue tracker is at: https://github.com/bambulab/BambuStudio/issues

It looks like a bug in the way the widgets are laid out in the app, and it's also very similar to an earlier bug that was fixed: https://github.com/bambulab/BambuStudio/issues/3605
