### ISSUE TITLE
Automatic flow dynamics and flow rate is not available

### ISSUE THREAD

**Issue by Nightfirecat** [flathub/com.bambulab.BambuStudio#30]
When connected to my A1 mini, the automatic flow dynamics and flow rate buttons do not appear under the calibration sections, instead showing only the following options:

* Flow dynamics:
  ![Screenshot_20240708_135032](https://github.com/flathub/com.bambulab.BambuStudio/assets/2199511/f8a1b52b-d870-4a6e-9c32-b71f414b39e7)
* Flow rate:
  ![Screenshot_20240708_135039](https://github.com/flathub/com.bambulab.BambuStudio/assets/2199511/13a5188d-e212-4fa7-b09f-0d4eb2108911)

**Comment by hadess** [comment]
That was normal, and not something related to Flatpak, as this was listed as one of the bug fixes in 1.10.0 beta:
> Auto calibration for A series: A-series printers now support auto-calibration triggering from the calibration page.(Supported A-series firmware version:01.04.00.00）

See 6. at https://github.com/bambulab/BambuStudio/releases/tag/v01.10.00.74

Follow the instructions in this if you want to test a beta version:
https://github.com/flathub/com.bambulab.BambuStudio/pull/37#issuecomment-2419836481

And file a new issue at https://github.com/bambulab/BambuStudio/issues if this is still a problem.
