### ISSUE TITLE
bambu studio network plugin issue

### ISSUE THREAD

**Issue by samwalker12** [flathub/com.bambulab.BambuStudio#40]
hi
![17306824115108505515196511100676](https://github.com/user-attachments/assets/6decd1f0-0786-4a21-a52c-789711f9c4b3)
![17306824302161401398415710610022](https://github.com/user-attachments/assets/2ca985db-b229-41ae-8cb0-4e8427dcb5c8)
![17306824559094413076672200134317](https://github.com/user-attachments/assets/dc4de147-da85-4656-b462-30751c9873d9)
 every time i launch bambu studio it says [network plugin not detected click here to download it] i click in it says installed successfully yet still can not detect it yet it has them in the config folder  please help me. also im on raspi os bookworm  it is debian based os thanks.

**Comment by hadess** [comment]
There's no ARM64 version of the plugin:
https://github.com/bambulab/BambuStudio/issues/4658

This will need to be fixed by BambuLabs themselves in that bug, so closing.

**Comment by samwalker12** [comment]
I would be up for it

Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
