### ISSUE TITLE
Blurry overlays and toasts since 1.8.4

### ISSUE THREAD

**Issue by jgraichen** [flathub/com.bambulab.BambuStudio#5]
Since the 1.8.4 update, toast messages and overlay dialogs, such as slicing details, are heavily blurred. This does not happen with the 1.8.4 AppImage.

See the marked areas in the enlarged screenshots:

Flatpak 1.8.4:

![Screenshot from 2024-01-19 20-17-18](https://github.com/flathub/com.bambulab.BambuStudio/assets/800848/7cdf03a3-29c0-4f97-a28e-4f53a01f395b)

AppImage 1.8.4:

![Screenshot from 2024-01-19 20-12-51](https://github.com/flathub/com.bambulab.BambuStudio/assets/800848/33482028-7997-4f50-b0ec-d04d34faa013)

Environment:

```
> flatpak info com.bambulab.BambuStudio

Bambu Studio - Get perfect 3D prints!

          ID: com.bambulab.BambuStudio
         Ref: app/com.bambulab.BambuStudio/x86_64/stable
        Arch: x86_64
      Branch: stable
     Version: 1.8.4
     License: AGPL-3.0-only
      Origin: flathub
  Collection: org.flathub.Stable
Installation: system
   Installed: 663,0 MB
     Runtime: org.gnome.Platform/x86_64/45
         Sdk: org.gnome.Sdk/x86_64/45

      Commit: ec41415fb289fb142f1fe43348efe70627302b783a12f509939f8cae924b7009
      Parent: a7b36fe48a7e4108850fe6f56c5495a4dea9a01a4cf4b40808f65b7bd344a111
     Subject: Remove unused wxWidgets build option (44e3b653)
        Date: 2024-01-18 21:34:19 +0000
```

```
> lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 22.04.3 LTS
Release:	22.04
Codename:	jammy
```

**Comment by hadess** [comment]
https://github.com/bambulab/BambuStudio/issues/3416 is the upstream issue.

In both screenshots the problem is with the (heavily customised) ImGUI portion of the UI, not with the wxWidgets or GLFW parts of it. I can only reproduce the problem after updating GLFW (https://github.com/flathub/com.bambulab.BambuStudio/pull/4). I believe the ImGUI bits are rendered with GLFW, so maybe there was a change in the BambuStudio code, or in GLFW.

**Comment by jgraichen** [comment]
Thank you for looking. I had no graphic issue with the current AppImage on Ubuntu 22.04 LTS. That's why I reported it here. Is this because the AppImage uses a different (older) version of GLFW?

Shall I move over to the linked issue?

Note: I am not using fractional scaling.

**Comment by hadess** [comment]
There's a test build for the fix in https://github.com/flathub/com.bambulab.BambuStudio/pull/11

**Comment by jgraichen** [comment]
Thank you!

I've installed the test branch flatpakref mentioned there, and the overlays look good:

![image](https://github.com/flathub/com.bambulab.BambuStudio/assets/800848/d935a014-ed15-4c9a-9fea-0a1a8f37b74e)
